spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 13197060352-a8l8eoc50bqb9o79gtkbeqk7h1f2gugn.apps.googleusercontent.com
            client-secret:  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
            scope:
              - email
              - profile

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test;NON_KEYWORDS=USER,ORDER
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  #  file:
  #    path: ./
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
mail:
  address:

jwt:
  # 민감한 정보는 시스템 환경 변수에서 로드한다.






